name: Generate release-artifacts

on:
  workflow_dispatch:
  release:
    types: 
        - created
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: echo "skip test for now"

  just-want-to-try-ssh-connectivity:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.PRIVATE_KEY }}" >> private.pem
      - run: ssh -i ./private.pem root@47.254.236.60 docker ps
      
  releases-matrix:
    needs: test
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.29
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.18.linux-amd64.tar.gz"
        project_path: "./cmd"
        binary_name: "cmdr"
        extra_files: LICENSE README.md
